// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/exidioco/modules/joint/types
// ALIASGEN: github.com/exidioco/modules/joint/keeper
// ALIASGEN: github.com/exidioco/modules/joint/querier
package joint

import (
	"github.com/exidioco/modules/joint/keeper"
	"github.com/exidioco/modules/joint/querier"
	"github.com/exidioco/modules/joint/types"
)

const (
	EventTypeSetCount    = types.EventTypeSetCount
	EventTypeSet         = types.EventTypeSet
	EventTypeDeposit     = types.EventTypeDeposit
	AttributeKeyCount    = types.AttributeKeyCount
	AttributeKeyIdentity = types.AttributeKeyIdentity
	AttributeKeyConsents = types.AttributeKeyConsents
	ModuleName           = types.ModuleName
	QuerierRoute         = types.QuerierRoute
	RouterKey            = types.RouterKey
	StoreKey             = types.StoreKey
	QueryAccount         = types.QueryAccount
	QueryAccounts        = types.QueryAccounts
)

var (
	// functions aliases
	RegisterCodec          = types.RegisterCodec
	NewGenesisState        = types.NewGenesisState
	DefaultGenesisState    = types.DefaultGenesisState
	AccountKey             = types.AccountKey
	NewMsgCreate           = types.NewMsgCreate
	NewMsgDeposit          = types.NewMsgDeposit
	NewQueryAccountParams  = types.NewQueryAccountParams
	NewQueryAccountsParams = types.NewQueryAccountsParams
	NewKeeper              = keeper.NewKeeper
	NewQuerier             = querier.NewQuerier

	// variable aliases
	ModuleCdc                = types.ModuleCdc
	ErrorMarshal             = types.ErrorMarshal
	ErrorUnmarshal           = types.ErrorUnmarshal
	ErrorUnknownMessage      = types.ErrorUnknownMessage
	ErrorUnknownQuery        = types.ErrorUnknownQuery
	ErrorNegativeCoins       = types.ErrorNegativeCoins
	ErrorAccountDoesNotExist = types.ErrorAccountDoesNotExist
	EventModuleName          = types.EventModuleName
	CountKey                 = types.CountKey
	AccountKeyPrefix         = types.AccountKeyPrefix
)

type (
	Account             = types.Account
	Accounts            = types.Accounts
	GenesisState        = types.GenesisState
	MsgCreate           = types.MsgCreate
	MsgDeposit          = types.MsgDeposit
	QueryAccountParams  = types.QueryAccountParams
	QueryAccountsParams = types.QueryAccountsParams
	Keeper              = keeper.Keeper
)
