// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/exidioco/modules/joint/types
// ALIASGEN: github.com/exidioco/modules/joint/keeper
// ALIASGEN: github.com/exidioco/modules/joint/querier
package joint

import (
	"github.com/exidioco/modules/joint/keeper"
	"github.com/exidioco/modules/joint/querier"
	"github.com/exidioco/modules/joint/types"
)

const (
	EventTypeCreate      = types.EventTypeCreate
	EventTypeSend        = types.EventTypeSend
	EventTypeDeposit     = types.EventTypeDeposit
	EventTypeApprove     = types.EventTypeApprove
	AttributeKeyIdentity = types.AttributeKeyIdentity
	AttributeKeyConsents = types.AttributeKeyConsents
	AttributeKeyFrom     = types.AttributeKeyFrom
	AttributeKeyTo       = types.AttributeKeyTo
	AttributeKeyCoins    = types.AttributeKeyCoins
	AttributeKeyDeadline = types.AttributeKeyDeadline
	AttributeKeyHolder   = types.AttributeKeyHolder
	ModuleName           = types.ModuleName
	QuerierRoute         = types.QuerierRoute
	RouterKey            = types.RouterKey
	StoreKey             = types.StoreKey
	QueryAccount         = types.QueryAccount
	QueryAccounts        = types.QueryAccounts
	QueryTransfer        = types.QueryTransfer
	QueryTransfers       = types.QueryTransfers
)

var (
	// functions aliases
	RegisterCodec                   = types.RegisterCodec
	NewGenesisState                 = types.NewGenesisState
	DefaultGenesisState             = types.DefaultGenesisState
	AccountKey                      = types.AccountKey
	TransferKey                     = types.TransferKey
	GetTransferForDeadlineKeyPrefix = types.GetTransferForDeadlineKeyPrefix
	TransferForDeadlineKey          = types.TransferForDeadlineKey
	NewMsgCreate                    = types.NewMsgCreate
	NewMsgDeposit                   = types.NewMsgDeposit
	NewMsgSend                      = types.NewMsgSend
	NewMsgApprove                   = types.NewMsgApprove
	NewQueryAccountParams           = types.NewQueryAccountParams
	NewQueryAccountsParams          = types.NewQueryAccountsParams
	NewQueryTransferParams          = types.NewQueryTransferParams
	NewQueryTransfersParams         = types.NewQueryTransfersParams
	NewKeeper                       = keeper.NewKeeper
	NewQuerier                      = querier.NewQuerier

	// variable aliases
	ModuleCdc                    = types.ModuleCdc
	ErrorMarshal                 = types.ErrorMarshal
	ErrorUnmarshal               = types.ErrorUnmarshal
	ErrorUnknownMessage          = types.ErrorUnknownMessage
	ErrorUnknownQuery            = types.ErrorUnknownQuery
	ErrorNegativeCoins           = types.ErrorNegativeCoins
	ErrorAccountDoesNotExist     = types.ErrorAccountDoesNotExist
	ErrorTransferDoesNotExist    = types.ErrorTransferDoesNotExist
	ErrorDeadlineExceeded        = types.ErrorDeadlineExceeded
	ErrorTransferFulfilled       = types.ErrorTransferFulfilled
	ErrorDuplicateSigner         = types.ErrorDuplicateSigner
	ErrorHolderDoesNotExist      = types.ErrorHolderDoesNotExist
	EventModuleName              = types.EventModuleName
	AccountsCountKey             = types.AccountsCountKey
	AccountKeyPrefix             = types.AccountKeyPrefix
	TransfersCountKey            = types.TransfersCountKey
	TransferKeyPrefix            = types.TransferKeyPrefix
	TransferForDeadlineKeyPrefix = types.TransferForDeadlineKeyPrefix
)

type (
	Account              = types.Account
	Accounts             = types.Accounts
	GenesisState         = types.GenesisState
	MsgCreate            = types.MsgCreate
	MsgDeposit           = types.MsgDeposit
	MsgSend              = types.MsgSend
	MsgApprove           = types.MsgApprove
	QueryAccountParams   = types.QueryAccountParams
	QueryAccountsParams  = types.QueryAccountsParams
	QueryTransferParams  = types.QueryTransferParams
	QueryTransfersParams = types.QueryTransfersParams
	Transfer             = types.Transfer
	Transfers            = types.Transfers
	Keeper               = keeper.Keeper
)
